- hosts: localhost
  connection: local
  become: True
  become_user: root
  become_method: sudo  
  pre_tasks:
    - name: Add copyq apt repository
      apt_repository:
        repo: ppa:hluk/copyq

    - name: Install dependecies
      apt:
        name:
          - cbatticon #battery indicator
          - copyq
          - coreutils #timeout
          - elixir
          - eza
          - fd-find
          - feh
          - flameshot
          - fontconfig
          - git
          - gimp
          - i3lock
          - keychain
          - libfuse2
          - light
          - pavucontrol
          - picom
          - python3.12-venv
          - ranger
          - redshift
          - rsync
          - x11-xkb-utils #keyboard pl
          - xclip
          - tmux
          - vim

    - name: mkdir ~/.tmux/plugins
      become: false
      file:
        path: "{{ user_home }}/.tmux/plugins"
        state: directory

    - name: Clone the tpm repository
      become: false
      git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: "{{ user_home}}/.tmux/plugins/tpm"

    - name: Check if GPG key exists
      become: false
      command: "gpg --list-secret-keys {{ gpg_id }}"
      register: gpg_key_check
      changed_when: gpg_key_check.rc != 0
      failed_when: false

    - name: Import GPG
      become: false
      ansible.builtin.shell: "op document get {{ op_gpg_id }} | gpg --import"
      when: gpg_key_check.rc != 0

    - name: Set git config gpg sign
      become: false
      git_config:
        name: commit.gpgsign
        scope: global
        value: true

    - name: Set git config gpg key
      become: false
      git_config:
        name: user.signingkey
        scope: global
        value: "{{ gpg_id }}"

    - name: Brew> Install prereq deb packages for
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - build-essential
          - curl
          - file
          - git
          - procps 
          - locales
          - language-pack-en

    - name: Brew> Temporary directory
      ansible.builtin.file:
        path: "{{ linuxbrew_install_tmp }}"
        state: directory
        mode: 0700
      become: false

    - name: Brew> Download Homebrew install script
      ansible.builtin.get_url:
        url: "{{ linuxbrew_install_url }}"
        dest: "{{ linuxbrew_install_tmp }}/install.sh"
        checksum: "{{ linuxbrew_install_checksum | default(omit) }}"
        mode: 0700
      become: false

    - name: Brew> Install Homebrew with the installer
      ansible.builtin.command: sh -c "{{ linuxbrew_install_tmp }}/install.sh"
      register: install_result
      changed_when: "install_result.rc == 0"
      become: false

    - name: Brew> Remove temporary directory
      ansible.builtin.file:
        path: "{{ linuxbrew_install_tmp }}"
        state: absent
      become: false

    - name: Brew> Ensure taps are added
      homebrew_tap:
        name: "{{ item }}"
        state: present
        path: "{{ linuxbrew_prefix_shared }}/bin"
      loop:
        - jesseduffield/lazydocker
        - knqyf263/pet
        - jesseduffield/lazygit
        - wez/wezterm-linuxbrew
      become: false
          
    - name: Brew> Install Formula
      community.general.homebrew:
        name: 
          - bat
          - chezmoi  
          - entr
          - ripgrep
          - lazydocker
          - pet
          - git-delta
          - lazygit
          - pgcli
          - xsv
          - neovim
          - ouch
          - tmux
          - tmuxinator
          - httpie
          - diff-so-fancy
          - tree
          - tlrc
          - wezterm
          - zsh-autosuggestions
        state: present
        path: "{{ linuxbrew_prefix_shared }}/bin"
      become: false

    - name: Clone i3-volume
      git:
        repo: https://github.com/hastinbe/i3-volume.git
        dest: "{{ i3_volume_path }}"
        clone: yes
        update: no

    - name: Clone tmux-scripts
      git:
        repo: "{{ scripts_repo }}"
        dest: "{{ scripts_path }}"
        clone: yes
        update: yes

    - name: Copy dotfiles
      ansible.builtin.command:
        cmd: "chezmoi init --guess-repo-url=false --apply {{ chezmoi_repo }}"
        chdir: "{{ user_home }}"
        creates: "{{ chezmoi_source_dir  }}"

    - name: Install firefox
      community.general.snap:
        name:
          - firefox

    - name: Install crontab
      become: false
      ansible.builtin.cron:
        name: "Change wallpaper"
        minute: "1"
        job: "sh {{ scripts_path }}/wallpaper.sh 2>&1 | logger -t wall"

  roles:
    - vonmecheln.vivaldi
    - geerlingguy.docker
    - role: geerlingguy.nodejs
    - role: hurricanehrndz.nerdfonts
    - role: buluma.npm
      tags: now
    - role: gantsign.oh-my-zsh
      users:
        - username: radoslaw-klak

  vars:
    user_home: "/home/radoslaw-klak"
    docker_install_compose: true     
    linuxbrew_prefix_shared: "/home/linuxbrew/.linuxbrew"
    linuxbrew_use_installer: true
    linuxbrew_install_tmp: "/tmp/linuxbrew"
    linuxbrew_install_url: "https://raw.githubusercontent.com/Homebrew/install/master/install.sh"
    i3_volume_path: "/home/radoslaw-klak/i3-volume"
    scripts_path: "/home/radoslaw-klak/scripts"
    scripts_repo: "https://github.com/rklak/tmux-scripts.git"
    oh_my_zsh_write_zshrc: false
    chezmoi_repo: "https://github.com/rklak/dotfiles.git"
    chezmoi_source_dir: "{{ user_home }}/.local/share/chezmoi"
    nerdfonts_users: [radoslaw-klak]
    op_gpg_id: "nezivdzc5rcrgehnxm3cjjsx4q"
    gpg_id: "C9C883263380855C"
