roles:
  - name: vonmecheln.vivaldi
  - name: geerlingguy.docker
  - name: gantsign.oh-my-zsh
  - name: gantsign.ansible-role-golang
  - name: hurricanehrndz.nerdfonts
  - name: geerlingguy.nodejs
collections:
  - name: community.general
