roles:
  - name: vonmecheln.vivaldi
  - name: geerlingguy.docker
  - name: gantsign.oh-my-zsh
  - name: gantsign.golang
  - name: hurricanehrndz.nerdfonts
  - name: geerlingguy.nodejs
  - name: buluma.npm
collections:
  - name: community.general
